### ISSUE TITLE
Fucking awesome!

### ISSUE THREAD

**Issue by nextgenthemes** [majodev/google-webfonts-helper#11]
This is **the** project I searched for years. Thank you so much!

Fuck google and their purposely not letting us download this **open source fonts** in web formats in a easy way. They are obviously want ppl to use their caching servers with their stupidly crypted filenames so they can track ppl and collect all sorts of data from it. And they won as always, every stupid open source project is use google webfonts. Years of preach how great independent open source should be ... but then going for this crap.

Also developing locally with no Internet and google webfonts breaks the fonts. But everyone is running for it like crazy because its so easy - as always.

**Comment by davelab6** [comment]
Did you read https://developers.google.com/fonts/faq?hl=en#what-does-using-the-google-fonts-api-mean-for-the-privacy-of-my-users ? :)

**Comment by nextgenthemes** [comment]
@davelab6 No I did not, well since you gave me the link I now did. Not sure what you are trying to tell me. No surprises there, they tell they log ... make its sound so great by talking about how they not use cookies, track popularity ... and then they link to their general global Google terms nobody agrees to by visiting a website with Google fonts on it. In their terms they get real and there is all the stuff they don't mentioned b4. Its the "We track and abuse all the data about you in every possible way we can" in lawyer speech ;)

I am not buying anything Google tells me,  I do not care if they use cookies or not (technically they can not set cookies for requesting css and font files). They do not need any cookies to track your web movement, they have Google Analytics on pretty much the entire web as its sadly the de-facto standard. There they get all sorts of data, then they can combine this with the IP if visitors downloading fonts, at what time, at what sites, after coming from there ... and I am sure the ppl at Google have way more Ideas then me how to get as much userdata as possible.

**Comment by majodev** [comment]
Closing this issue as the discussion is no longer active (and not an issue anyways). I hope you 2 don't mind, thanks again for using and supporting this project! :100:

**Comment by nextgenthemes** [comment]
Oh I am sure the brainwashed googler @davelab6 dosn't mind, he has no arguments so he decided to not even try.

Funny the irony how this guys motto is "I free fonts".

**Comment by davelab6** [comment]
@nextgenthemes peace

**Comment by davelab6** [comment]
@nextgenthemes I wrote that text.

**Comment by davelab6** [comment]
> I do not care if they use cookies or not (technically they can not set cookies for requesting css and font files). 

Right, but some people mistakenly believe that GF uses cookies. 

> They do not need any cookies to track your web movement, they have Google Analytics on pretty much the entire web as its sadly the de-facto standard. There they get all sorts of data, then they can combine this with the IP if visitors downloading fonts, at what time, at what sites, after coming from there ... and I am sure the ppl at Google have way more Ideas then me how to get as much userdata as possible.

One CSS request per font family per browser per day yields very little 'user data.' 

> I just noticed you are in the Google organization here on Gihub, you worked for Google? 

I do not speak for Google, I work for the GF team as an independent consultant. 

> You let Google promote your fonts to get customers though that popularity? 

Google is my primary consulting client. 

> Good for you. But then you are probably brainwashed to believe and defend heir BS.

@.@

> Care to tell me why you are in the Google org and why you have this "I free fonts" slogan? Because its actually @majodev who is freeing the fonts here while you probably get payed by Google as a Adviser to tell them howto get more cools fonts in to then being locked down and then being used to help Google in to expand their privacy violations with them.

Please explain how you think Google Fonts 'locked down' the fonts?

@majodev has a nice project to redistribute libre fonts in a novel way, but he is not contributing to the development and publication of the libre fonts. 

> Its sad that they brainwash ppl like you who probably are very well meaning. I mean your non-profit about fonts sounds really nice I must say.

I'm confused; which non-profit are you referring to?

> You should learn a bit if critical thinking! 

I prefer to learn about the classical ideas of literacy - how to reading critically, writing persuasively, and orating entertainingly - rather than the diluted contemporary "critical thinking" discourse. 

> But you will probably call me with a CIA term now. Hey BTW Google was financed by the CIA and others. Another article I did not read yet but found during Googleing (oh the irony) for this comment/rant.

I read about this and was unsurprised. I also read and recommend Steven Levy's book on the history of the company. 

> Why is google only giving the TTF downloads away? 

In my personal opinion, this incentivises using the Fonts API.

> Are the build tools/process opened up and documented? I think not, on purpose of course! 

Yes, they are, actually. 

* https://github.com/googlei18n/sfntly
* https://github.com/google/woff2

> Why is google using this crypted filenames. 

The filenames are machine generated to be unique (across versions.) The Fonts Developer API provides the 'human' filenames.

> You can bust caching with version strings and server setups, there is absolutely no need for this cypted filename.

I don't understand what you mean. Could you explain with more detail?

> If you really want to free fonts then stop working for Google 

From time to time I do consider if I could have more impact on liberating typography by doing something else, but I have not yet seen such an opportunity. If you have ideas, please share them :) 

> or make them make this project obsolete by providing what this project is offering through the Google Webfonts site!

I will discuss this feedback with the GF team. Thanks!
