### ISSUE TITLE
Service is unavailable?

### ISSUE THREAD

**Issue by h3poteto** [majodev/google-webfonts-helper#46]
I can not open https://google-webfonts-helper.herokuapp.com. The website response is '503 Service Unavailable'.
What's happend?

**Comment by majodev** [comment]
I'm currently unable to properly update my payment details with heroku, I'm in touch with them...

Unfortunately if I can't resolve this, I'm afraid the service will be disabled until the end of March.

**Comment by SegersIan** [comment]
Shit happens, broke my build, but sh*t happens, wish you the best of luck and resolving this! 🕺🏻

**Comment by RomActive** [comment]
Your tool is so perfect @majodev ... A jewel for coders!
I hope you find a solution for you and for the good of the whole community! :)
Good luck !!  ;)

**Comment by majodev** [comment]
Resolved, up again.

**Comment by majodev** [comment]
Please keep in mind that this service is running since >3 years for **free** on heroku's infrastructure and I'm not actively monitoring the healthiness of the hosted service for its uptime (and **please** also refrain from doing so).

If this service is critical for your build infrastructure / CI / tooling, please setup a proxy. If it's public, I will happily mention it in the README.md.

**Comment by RomActive** [comment]
Fantastic !
Yes, I would like to install a proxy but I am not at all familiar with all that!
Is there some kind of "guide" to do that?

**Comment by SegersIan** [comment]
It was rather silly of me to have my CI depend on it, but that happens when you set up something ages ago 'quickly'. Got what I deserved 😂
